- name: Create a Directory in Debian System
  hosts: localhost
  become: yes

  tasks:
  - name: Create a www directory under /srv
    file:
     path: "/srv/www"
     state: directory
     mode: 0755
    when: ansible_facts['os_family'] == "Debian"
