- name: Run one task in play using tags
  hosts: remotehost
  become: yes
  gather_facts: no
  
  tasks: 
  - name: install httpd
    apt:
     name: "{{ item }}"
     state: present
    with_items:
     - httpd
    tags: apache

  - name: install nginx
    apt:
     name: "{{ item }}"
     state: present
    with_items:
      - nginx
    tags: nginx   

