- name: Create user
  hosts: remotehost
  become: yes
  gather_facts: no

  vars:
   pwd: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"

  tasks:
  - set_fact:
        my_pass: "{{ pwd }}"

  - debug:
        msg: "{{ my_pass }}"

  - name: Create kiran user
    user:
     name: kp369d
     password: "{{ my_pass }}"
     update_password: on_create
